version: "3"
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    networks:
      rabbitmq_net:
        ipv4_address: 172.20.0.2
    ports:
#      - "15672:15672"
      - "5675:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Admin@123
      RABBITMQ_ERLANG_COOKIE: rabbitcookie
    restart: always
    volumes:
      - ./rabbitmq1/data:/var/lib/rabbitmq/mnesia

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    networks:
      rabbitmq_net:
        ipv4_address: 172.20.0.3
    ports:
      - "5673:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitcookie
    restart: always
    volumes:
      - ./rabbitmq2/data:/var/lib/rabbitmq/mnesia

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    networks:
      rabbitmq_net:
        ipv4_address: 172.20.0.4
    ports:
      - "5674:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitcookie
    restart: always
    volumes:
      - ./rabbitmq3/data:/var/lib/rabbitmq/mnesia

networks:
  rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

